{
  "name": "blockchain-charity-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "chain": "hardhat node",
    "compile": "hardhat compile",
    "deploy": "hardhat run scripts/deploy.js --network localhost",
    "deploy:goerli": "hardhat run scripts/deploy.js --network goerli",
    "test": "hardhat test",
    "test:frontend": "jest --watch",
    "generate:graph": "graph codegen",
    "deploy:graph": "graph deploy --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ <your-subgraph-name>",
    "verify": "hardhat run scripts/verify.js --network goerli"
  },
  "dependencies": {
    "@apollo/client": "^3.7.0",
    "@ethersproject/providers": "^5.7.0",
    "@graphprotocol/graph-cli": "^0.37.1",
    "@graphprotocol/graph-ts": "^0.29.1",
    "@headlessui/react": "^1.7.0",
    "@heroicons/react": "^2.0.13",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/line-clamp": "^0.4.2",
    "axios": "^1.2.0",
    "ethers": "^5.7.2",
    "graphql": "^16.6.0",
    "ipfs-http-client": "^56.0.3",
    "next": "^13.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.40.0",
    "react-query": "^3.39.2",
    "swr": "^1.3.0",
    "web3": "^1.8.1",
    "web3modal": "^1.9.9"
  },
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^2.0.0",
    "@tailwindcss/typography": "^0.5.7",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@types/node": "^18.11.9",
    "@types/react": "^18.0.25",
    "@types/react-dom": "^18.0.9",
    "autoprefixer": "^10.4.13",
    "dotenv": "^16.0.3",
    "eslint": "^8.28.0",
    "eslint-config-next": "13.0.6",
    "hardhat": "^2.12.0",
    "hardhat-deploy": "^0.11.20",
    "hardhat-gas-reporter": "^1.0.9",
    "jest": "^29.3.1",
    "postcss": "^8.4.20",
    "prettier": "^2.8.0",
    "prettier-plugin-solidity": "^1.1.1",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.3"
  }
}